[package]
name = "asciilife"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
ratatui = { version = "0.28.1", features = ["all-widgets", "serde"] }
serde = "1.0.210"
